#pragma once

#include <string>
#include <memory>
#include <windows.h>
#include <time.h>
#include<cmath>
#include <iterator>
#include <stdexcept>
#include <optional>
#include <vector>
#include <map>
#include <unordered_map>
#include <utility>
#include <any>
#include <queue>
#include <set>
#include <cstdint>
#include <algorithm>
#include <fstream>
#include <array>
#include <filesystem>
#include <format>
#include <string_view>
#include <iostream>
#include <mutex>
#include <functional>
#include <future>
#include <typeinfo>
#include <sstream> 
#include <variant>
#include <unordered_set>
#include <stack>
